services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: tf2modportal_app
        command: "python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8010:8000"
        volumes:
            - ./src/:/app/
        env_file:
            - .env
        restart: unless-stopped
        depends_on:
            - db
        networks:
            - tf2modportal-network
    celery:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: tf2modportal_celery
        command: celery -A tf2modportal worker --loglevel=info
        volumes:
            - ./src//:/app/
        env_file:
            - .env
        restart: unless-stopped
        depends_on:
            - app
            - db
            - redis
        networks:
            - tf2modportal-network
    celery_beat:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: tf2modportal_celery_beat
        command: celery -A tf2modportal beat --loglevel=info
        volumes:
            - ./src//:/app/
        env_file:
            - .env
        restart: unless-stopped
        depends_on:
            - app
            - db
            - redis
        networks:
            - tf2modportal-network
    db:
        image: postgres:15.1
        container_name: tf2modportal_db
        env_file:
            - .env
        restart: unless-stopped
        ports:
            - "5444:5432"
        networks:
            - tf2modportal-network
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 30s
            timeout: 30s
            retries: 3
    redis:
        image: "redis:alpine"
        container_name: tf2modportal_redis
        command: redis-server --requirepass ${REDIS_PASSWORD}
        env_file:
            - .env
        restart: unless-stopped
        expose:
            - "6380:6379"
        networks:
            - tf2modportal-network
        healthcheck:
            test: [ "CMD-SHELL", "redis-cli ping || exit 1" ]
            interval: 30s
            timeout: 30s
            retries: 3

networks:
    tf2modportal-network: