# Generated by Django 5.1 on 2024-08-24 20:01

import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaMod',
            fields=[
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=31, prefix='metamod_', primary_key=True, serialize=False, unique=True)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('windows_file', models.FileField(blank=True, null=True, upload_to='downloads/metamod/windows/')),
                ('linux_file', models.FileField(blank=True, null=True, upload_to='downloads/metamod/linux/')),
            ],
        ),
    ]
