# Generated by Django 5.1 on 2024-08-29 14:42

import prefix_id.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metamod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metamod',
            name='id',
            field=prefix_id.field.PrefixIDField(editable=False, max_length=30, prefix='metamod', primary_key=True, serialize=False, unique=True),
        ),
    ]
