# Generated by Django 5.1 on 2024-08-24 20:48

import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=30, prefix='plugin_', primary_key=True, serialize=False, unique=True)),
                ('plugin_source', models.CharField(choices=[('sourcemod', 'SourceMod'), ('github', 'GitHub')], default='sourcemod', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('smx_file', models.FileField(blank=True, null=True, upload_to='downloads/plugins/')),
                ('sp_file', models.FileField(blank=True, null=True, upload_to='downloads/plugins/')),
                ('cfg_file', models.FileField(blank=True, null=True, upload_to='downloads/plugins/')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='downloads/plugins/')),
            ],
        ),
    ]
