# Generated by Django 5.1 on 2024-08-25 10:27

import django.db.models.deletion
import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=32, prefix='category_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportedGame',
            fields=[
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=28, prefix='game_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('app_id', models.IntegerField()),
                ('icon', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='cfg_file',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='smx_file',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='sp_file',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='zip_file',
        ),
        migrations.AddField(
            model_name='plugin',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='short_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plugin',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='plugins.category'),
        ),
        migrations.CreateModel(
            name='PluginFile',
            fields=[
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=35, prefix='plugin_file_', primary_key=True, serialize=False, unique=True)),
                ('file_type', models.CharField(choices=[('smx', 'SourceMod Plugin'), ('sp', 'SourcePawn Script'), ('cfg', 'Configuration File'), ('zip', 'Zip Archive')], default='smx', max_length=50)),
                ('file', models.FileField(upload_to='downloads/plugins/')),
                ('download_url', models.URLField(blank=True, null=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='plugins.plugin')),
            ],
        ),
        migrations.AddField(
            model_name='plugin',
            name='supported_games',
            field=models.ManyToManyField(related_name='plugins', to='plugins.supportedgame'),
        ),
    ]
