# Generated by Django 5.1 on 2024-08-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_category_supportedgame_remove_plugin_cfg_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='downloads/plugins/'),
        ),
    ]
