# Generated by Django 5.1 on 2024-08-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0003_alter_pluginfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginfile',
            name='file_name',
            field=models.CharField(default='plugin.smx', max_length=50),
        ),
    ]
