# Generated by Django 5.1 on 2024-08-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0004_pluginfile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
