# Generated by Django 5.1 on 2024-08-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0005_alter_plugin_author_alter_plugin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='short_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='version',
            field=models.CharField(max_length=255),
        ),
    ]
