# Generated by Django 5.1 on 2024-08-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0006_alter_plugin_short_id_alter_plugin_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pluginfile',
            name='file_name',
            field=models.CharField(default='plugin.smx', max_length=255),
        ),
        migrations.AlterField(
            model_name='pluginfile',
            name='file_type',
            field=models.CharField(choices=[('smx', 'SourceMod Plugin'), ('sp', 'SourcePawn Script'), ('cfg', 'Configuration File'), ('zip', 'Zip Archive')], default='smx', max_length=255),
        ),
        migrations.AlterField(
            model_name='supportedgame',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
