# Generated by Django 5.1 on 2024-08-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0007_alter_category_name_alter_pluginfile_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
