# Generated by Django 5.1 on 2024-08-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0009_remove_pluginfile_plugin_tag_pluginfile_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pluginfile',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='tags_files', to='plugins.pluginfile'),
        ),
    ]
