# Generated by Django 5.1 on 2024-08-26 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0010_remove_pluginfile_tag_tag_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='files',
        ),
        migrations.AddField(
            model_name='pluginfile',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='plugins.tag'),
        ),
    ]
