# Generated by Django 5.1 on 2024-08-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0012_plugin_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='archive_file',
            field=models.FileField(blank=True, null=True, upload_to='downloads/plugins/'),
        ),
    ]
