# Generated by Django 5.1 on 2024-08-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0013_tag_archive_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='archive_file',
            field=models.FileField(blank=True, null=True, upload_to='downloads/plugins'),
        ),
    ]
