# Generated by Django 5.1 on 2024-08-29 14:42

import prefix_id.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0014_alter_tag_archive_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=prefix_id.field.PrefixIDField(editable=False, max_length=31, prefix='category', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='id',
            field=prefix_id.field.PrefixIDField(editable=False, max_length=29, prefix='plugin', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pluginfile',
            name='id',
            field=prefix_id.field.PrefixIDField(editable=False, max_length=34, prefix='plugin_file', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='supportedgame',
            name='id',
            field=prefix_id.field.PrefixIDField(editable=False, max_length=27, prefix='game', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=prefix_id.field.PrefixIDField(editable=False, max_length=26, prefix='tag', primary_key=True, serialize=False, unique=True),
        ),
    ]
