# Generated by Django 5.1 on 2024-09-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0015_alter_category_id_alter_plugin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginfile',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='downloads/plugins/'),
        ),
    ]
