# Generated by Django 5.1 on 2024-09-01 23:45

import prefix_id.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_remove_build_plugins_build_plugins_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='id',
            field=prefix_id.field.PrefixIDField(editable=False, max_length=28, prefix='build', primary_key=True, serialize=False, unique=True),
        ),
    ]
