# Generated by Django 5.1 on 2024-08-24 18:59

import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceMod',
            fields=[
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=33, prefix='sourcemod_', primary_key=True, serialize=False, unique=True)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('file', models.FileField(upload_to='sourcemod/')),
            ],
        ),
    ]
