# Generated by Django 5.1 on 2024-08-29 14:42

import prefix_id.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcemod', '0003_alter_sourcemod_linux_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemod',
            name='id',
            field=prefix_id.field.PrefixIDField(editable=False, max_length=32, prefix='sourcemod', primary_key=True, serialize=False, unique=True),
        ),
    ]
